export const properties = [
    [0,{"GO": "white"}],
    [0,{"Mediterranean Avenue":"brown"}],
    [0,{"Community Chest 1": "gray"}],
    [0,{"Baltic Avenue":"brown"}],
    [0,{"Tax 1": "darkGray"}],
    [0,{"Reading Railroad":"black"}],
    [0,{"Oriental Avenue":"lightBlue"}],
    [0,{"Chance 1": "gray"}],
    [0,{"EVermont Avenue":"lightBlue"}],
    [0,{"Connecticut Avenue":"lightBlue"}],
    [0,{"Visit Jail": "gray"}],
    [0,{"St. Charles Place":"pink"}],
    [0,{"Electric Company": "purple"}],
    [0,{"States Avenue":"pink"}],
    [0,{"Virginia Avenue":"pink"}],
    [0,{"B. & O. Railroad":"black"}],
    [0,{"St. James Place":"orange"}],
    [0,{"Community Chest 2": "gray"}],
    [0,{"Tennessee Avenue":"orange"}],
    [0,{"New York Avenue":"orange"}],
    [0,{"Free Parking": "gray"}],
    [0,{"Kentucky Avenue":"red"}],
    [0,{"Chance 2": "gray"}],
    [0,{"Indiana Avenue":"red"}],
    [0,{"Illinois Avenue":"red"}],
    [0,{"Pennsylvania Railroad":"black"}],
    [0,{"Atlantic Avenue":"yellow"}],
    [0,{"Ventnor Avenue":"yellow"}],
    [0,{"Go to Jail": "gray"}],
    [0,{"Water Works": "purple"}],
    [0,{"Marvin Gardens":"yellow"}],
    [0,{"Pacific Avenue":"green"}],
    [0,{"North Carolina Avenue":"green"}],
    [0,{"Community Chest 3": "gray"}],
    [0,{"Pennsylvania Avenue":"green"}],
    [0,{"Short Line":"black"}],
    [0,{"Chance 3": "gray"}],
    [0,{"Park Place":"darkBlue"}],
    [0,{"Tax 1": "darkGray"}],
    [0,{"Boardwalk":"darkBlue"}],
]